# Generated by Django 3.2.9 on 2021-11-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namedata', models.CharField(max_length=200)),
                ('zonedata', models.TextField()),
                ('numberdata', models.IntegerField()),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='myapp.booked')),
            ],
        ),
    ]
